#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Supports: Linux

if [ -z "${inetdincluded}" ]
then

inetdincluded=1

. lib/misc/validate

inetd_list () {
	egrep -v "^#|^$" "/etc/inetd.conf" | while read portnumber sockettype protocol flags userid command arguments argumentsarguments
	do
		printf -- "${portnumber}-${protocol}\n";
	done
}

inetd_show_command () {
	pattern="${1}"
	[ "`validate_is_string \"${pattern}\"`" ] || false
	egrep -v "^#|^$" "/etc/inetd.conf" | while read portnumber sockettype protocol flags userid command arguments argumentsarguments
	do
		if [ "${portnumber}-${protocol}" = "${pattern}" ]
		then
			printf -- "${command}\n"
		fi
	done
}

inetd_show_userid () {
	pattern="${1}"
	[ "`validate_is_string \"${pattern}\"`" ] || false
	egrep -v "^#|^$" "/etc/inetd.conf" | while read portnumber sockettype protocol flags userid command arguments argumentsarguments
	do
		if [ "${portnumber}-${protocol}" = "${pattern}" ]
		then
			printf -- "${userid}\n"
		fi
	done
}

inetd_show_arguments () {
	pattern="${1}"
	[ "`validate_is_string \"${pattern}\"`" ] || false
	egrep -v "^#|^$" "/etc/inetd.conf" | while read portnumber sockettype protocol flags userid command arguments argumentsarguments
	do
		if [ "${portnumber}-${protocol}" = "${pattern}" ]
		then
			printf -- "${arguments}\n"
		fi
	done
}

fi
