#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Supports: Linux

if [ -z "${permissionincluded}" ]
then

permissionincluded=1

. lib/misc/validate

permission_is_owner_readable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^.r........$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_owner_writable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^..w.......$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_owner_executable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^...x......$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_group_readable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^....r.....$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_group_writable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^.....w....$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_group_executable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^......x...$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_world_readable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^.......r..$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_world_writable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^........w.$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_world_writable_sticky_bit () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^........wt$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

permission_is_world_executable () {
	permissions="${1}"
	[ "`validate_is_string \"${permissions}\"`" ] || false
	if [ -n "`printf -- \"${permissions}\" | egrep -- \"^.........x$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

fi
