#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# List users with no password set or password in /etc/passwd

. lib/misc/stdio
. lib/misc/passwd

passwd_hashes_init () {
	stdio_message_log "passwd_hashes" "Starting at: `date`"
}

passwd_hashes_main () {
	passwd_list | while read username
	do
		if [ "${username}" = "+" ]
		then
			stdio_message_warn "passwd_hashes" "/etc/passwd allows external authentication"
		else
			hash="`passwd_show_hash "${username}"`"
			if [ "${hash}" != "x" -a "${hash}" != "\!" -a "${hash}" != "*" ]
			then
				if [ -z "${hash}" ]
				then
					stdio_message_warn "passwd_hashes" "${username} has no password set"
				else
					stdio_message_warn "passwd_hashes" "/etc/passwd contains password hash for ${username} (${hash})"
				fi
			fi
		fi
	done
}

passwd_hashes_fini () {
	stdio_message_log "passwd_hashes" "Ending at: `date`"
}
