#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check if textual privileged files (like bash scripts) accept user-provided
# arguments

. lib/misc/stdio
. lib/misc/privileged
. lib/misc/binary

privileged_arguments_init () {
	stdio_message_log "privileged_arguments" "Starting at: `date`"
}

privileged_arguments_main () {
	privileged_list | while read filetype filename usergroupid
	do
		# skip non textual files
		if [ "`file_is_textual \"${filename}\"`" -ne 1 ]
		then
			continue
		elif [ "`binary_matches_string_grep \"${filename}\" \"\$[\{]*[[:digit:]][\}]*\"`" -eq 1 ]
		then
			stdio_message_warn "privileged_arguments" "${filetype} ${filename} (${usergroupid}) accepts arguments, verify that it does not use them unsafely"
		fi
	done
}

privileged_arguments_fini () {
	stdio_message_log "privileged_arguments" "Ending at: `date`"
}
