#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check for stack canary (SSP) support

. lib/misc/stdio
. lib/misc/privileged
. lib/misc/binary

privileged_ssp_init () {
	stdio_message_log "privileged_ssp" "Starting at: `date`"
}

privileged_ssp_main () {
	privileged_list | while read filetype filename usergroupid
	do
		if [ "`binary_matches_function "${filename}" "__stack_chk_fail"`" -ne 1 ]
		then
			stdio_message_warn "privileged_ssp" "${filetype} ${filename} (${usergroupid}) and is not compiled with SSP (Stack Smashing Protector)"
		fi
	done
}

privileged_ssp_fini () {
	stdio_message_log "privileged_ssp" "Ending at: `date`"
}
