#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check if SELinux enforces system-wide

. lib/misc/kernel
. lib/misc/stdio

system_selinux_init () {
	stdio_message_log "system_selinux" "Starting at: `date`"
}

system_selinux_main () {
	if [ "`kernel_selinux_enforce`" -eq 0 ]
	then
		stdio_message_warn "system_selinux" "SELinux does not enforce system-wide"
	else
		stdio_message_debug "system_selinux" "SELinux enforces system-wide"
	fi
}

system_selinux_fini () {
	stdio_message_log "system_selinux" "Ending at: `date`"
}
