#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# List world-writable files

. lib/misc/stdio
. lib/misc/file
. lib/misc/permission

world_writable_init () {
	stdio_message_log "world_writable" "Starting at: `date`"
}

world_writable_main () {
	file_show_non_symlink_perms "^........w. " | while read filename permissions userid groupid
	do
		case "${permissions}" in
			????????w?)
				if [ "`permission_is_world_writable_sticky_bit \"${permissions}\"`" -eq 1 ]
				then
					stdio_message_warn "world_writable" "${filename} is owned by user ${userid} (group ${groupid}) and is world-writable with sticky bit (${permissions})"
				else
					stdio_message_warn "world_writable" "${filename} is owned by user ${userid} (group ${groupid}) and is world-writable (${permissions})"
				fi
				;;
		esac
	done
}

world_writable_fini () {
	stdio_message_log "world_writable" "Ending at: `date`"
}
